@BCVP.Net8_HostAddress = http://localhost:5047

GET {{BCVP.Net8_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzA1MjQ0MDA1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNC8xLzE0IDE1OjUzOjI0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTcwNTIxNTIwNSwiZXhwIjoxNzA1MjE4ODA1LCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.rxjAGwFJsO8Ths6Mm0H5bUXuHH2S-z32JahPZVpDjXI

###
