@BCVP.Net8_HostAddress = http://localhost:5047
@BCVP.Net8_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjEwMDAwMDEiLCJpYXQiOiIxNzA4MzUyODE1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMDIvMTkvMjAyNCAxNToyNjo1NSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN1cGVyQWRtaW4iLCJuYmYiOjE3MDgzMjQwMTUsImV4cCI6MTcwODMyNzYxNSwiaXNzIjoiQmxvZy5Db3JlIiwiYXVkIjoid3IifQ.7Z03-4sjmc62Px5tMOEaujdduLS5Gcfkj8l0AOKzRhw

GET {{BCVP.Net8_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer {{BCVP.Net8_Token}}

###


GET {{BCVP.Net8_HostAddress}}/api/User/Get
Accept: application/json
Authorization:Bearer {{BCVP.Net8_Token}}

###

GET {{BCVP.Net8_HostAddress}}/api/User/Get/1
Accept: application/json
Authorization:Bearer {{BCVP.Net8_Token}}

###

GET {{BCVP.Net8_HostAddress}}/api/Tenant/GetAll
Accept: application/json
Authorization:Bearer {{BCVP.Net8_Token}}
