@BCVP.Net8_HostAddress = http://localhost:5047

GET {{BCVP.Net8_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMSIsIlRlbmFudElkIjoiMCIsImlhdCI6IjE3MDU0MTM1NjgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL2V4cGlyYXRpb24iOiIyMDI0LzEvMjYgMTM6NTk6MjgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlckFkbWluIiwibmJmIjoxNzA1Mzg0NzY5LCJleHAiOjE3MDYyNDg3NjksImlzcyI6IkJsb2cuQ29yZSIsImF1ZCI6IndyIn0.Rpem8s5fE8j7Q_sMTnzmRK5UgtANZVIVEYbybbt9T54

###
